-- Supabase SQL: 服务器端存储健身打卡 JSON
create table if not exists public.fitness_sync (
  id bigint generated by default as identity primary key,
  sync_code text not null,
  page_prefix text not null,
  payload jsonb not null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists fitness_sync_sync_code_page_prefix_idx
  on public.fitness_sync(sync_code, page_prefix);

alter table public.fitness_sync enable row level security;

-- 先放开匿名读写（够你现在这个个人页面先跑起来）
drop policy if exists "anon read fitness_sync" on public.fitness_sync;
create policy "anon read fitness_sync"
on public.fitness_sync
for select
to anon
using (true);

drop policy if exists "anon insert fitness_sync" on public.fitness_sync;
create policy "anon insert fitness_sync"
on public.fitness_sync
for insert
to anon
with check (true);

drop policy if exists "anon update fitness_sync" on public.fitness_sync;
create policy "anon update fitness_sync"
on public.fitness_sync
for update
to anon
using (true)
with check (true);
