create table if not exists public.workout_states (
  id bigint generated by default as identity primary key,
  app text not null,
  owner_hash text not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(app, owner_hash)
);

create or replace function public.touch_workout_states_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_workout_states_updated_at on public.workout_states;
create trigger trg_workout_states_updated_at
before update on public.workout_states
for each row execute function public.touch_workout_states_updated_at();

alter table public.workout_states enable row level security;

drop policy if exists "allow anon select by key" on public.workout_states;
create policy "allow anon select by key"
on public.workout_states
for select
using (true);

drop policy if exists "allow anon upsert by key" on public.workout_states;
create policy "allow anon upsert by key"
on public.workout_states
for insert
with check (true);

drop policy if exists "allow anon update by key" on public.workout_states;
create policy "allow anon update by key"
on public.workout_states
for update
using (true)
with check (true);

create or replace function public.save_workout_state(
  p_app text,
  p_owner_hash text,
  p_payload jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.workout_states(app, owner_hash, payload)
  values (p_app, p_owner_hash, coalesce(p_payload, '{}'::jsonb))
  on conflict (app, owner_hash)
  do update set
    payload = excluded.payload,
    updated_at = now();
end;
$$;

grant execute on function public.save_workout_state(text, text, jsonb) to anon, authenticated;

create or replace function public.load_workout_state(
  p_app text,
  p_owner_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_payload jsonb;
begin
  select payload into v_payload
  from public.workout_states
  where app = p_app and owner_hash = p_owner_hash
  limit 1;

  return v_payload;
end;
$$;

grant execute on function public.load_workout_state(text, text) to anon, authenticated;
